import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-main" lang="en">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1 overflow-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
